// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NormiesRe.Models;

namespace NormiesRe.Migrations
{
    [DbContext(typeof(NormiesDbContext))]
    [Migration("20180817205759_CommentCountryFlag")]
    partial class CommentCountryFlag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("NormiesRe.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Country");

                    b.Property<int?>("PostID");

                    b.Property<DateTime>("ReleaseDate");

                    b.HasKey("ID");

                    b.HasIndex("PostID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("NormiesRe.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Country");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("NormiesRe.Models.Comment", b =>
                {
                    b.HasOne("NormiesRe.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID");
                });
#pragma warning restore 612, 618
        }
    }
}
